/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BiometricsLiveness {
    'apiKey': string;
    'autoStart': boolean;
    'maxInstructions': number;
    'maxPictureHeight': number;
    'maxPictureWidth': number;
    'serverUrl': string;
    'showInitButton': boolean;
    'timeout': number;
  }
}

declare global {


  interface HTMLBiometricsLivenessElement extends Components.BiometricsLiveness, HTMLStencilElement {}
  var HTMLBiometricsLivenessElement: {
    prototype: HTMLBiometricsLivenessElement;
    new (): HTMLBiometricsLivenessElement;
  };
  interface HTMLElementTagNameMap {
    'biometrics-liveness': HTMLBiometricsLivenessElement;
  }
}

declare namespace LocalJSX {
  interface BiometricsLiveness {
    'apiKey'?: string;
    'autoStart'?: boolean;
    'maxInstructions'?: number;
    'maxPictureHeight'?: number;
    'maxPictureWidth'?: number;
    'serverUrl'?: string;
    'showInitButton'?: boolean;
    'timeout'?: number;
  }

  interface IntrinsicElements {
    'biometrics-liveness': BiometricsLiveness;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'biometrics-liveness': LocalJSX.BiometricsLiveness & JSXBase.HTMLAttributes<HTMLBiometricsLivenessElement>;
    }
  }
}


